AWSTemplateFormatVersion: '2010-09-09'
Description: 'Module 11 Lab - S3 bucket with versioning and encryption'

Parameters:
  BucketName:
    Type: String
    Default: module11-lab-bucket
    Description: Name for the S3 bucket (must be globally unique)

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketName}-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref S3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"
  
  BucketArn:
    Description: ARN of the created S3 bucket
    Value: !GetAtt S3Bucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-BucketArn"
  
  EncryptionStatus:
    Description: Encryption status of the S3 bucket
    Value: "AES256 Server-Side Encryption Enabled"